### ISSUE TITLE
GoCD elastic agent/cluster profile misconfigured

### ISSUE THREAD

**Issue by NikoHeikki** [gocd/kubernetes-elastic-agents#108]
I deployed GoCD kubernetes helm chart into Openshift OKD. GoCD automatically created cluster profile on startup but It didnt work, since status report or scheduling didnt work.

The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to handle request cd.go.elastic-agent.server-ping'

Failed to handle request cd.go.elastic-agent.cluster-status-report

Then I modified cluster profile I changed cluster url to point to url I got from running "kubectl cluster-info", before it was some internal cluster ip

I changed security token to gocd namespace default secret and I tried with gocd-app secret token created by helm, didnt work

**Comment by GaneshSPatil** [comment]
@NikoHeikki, Hello,

What steps did we follow to install GoCD Helm chart on Openshift OKD?

Did we configure the service account? The `cluster-admin` role is a cluster level role that exists on Openshift OKD. We need to associate the cluster role with the service account with a cluster role binding.

```
kubectl create clusterrolebinding clusterRoleBinding \
--clusterrole=cluster-admin \
--serviceaccount=kube-system:default
 ```

**Comment by NikoHeikki** [comment]
Issue solved by adding correct ca certificate to cluster profile!

**Comment by GaneshSPatil** [comment]
@NikoHeikki -- Thanks for the information.

Though, ideally, GoCD should configure the appropriate ca certificate too!

\cc: @adityasood

**Comment by varshavaradarajan** [comment]
@GaneshSPatil - the properties that are configured for the cluster are `go_server_url`, `kubernetes_cluster_url`, `namespace` and `security_token`  as per https://github.com/helm/charts/commit/740778be04d6fcc4de38163f3fdcb99512a9e971 . The reason was that we wanted to provide the minimal amount of configuration for this to work on aws, gce, minikube.
