### ISSUE TITLE
Broken help link

### ISSUE THREAD

**Issue by ketan** [gocd/kubernetes-elastic-agents#111]
Here: https://github.com/gocd/kubernetes-elastic-agents/blob/8d29fa51217424f0804af8c82f44404efde8956f/src/main/resources/profile.template.html#L210

**Comment by arvindsv** [comment]
Maybe it should point to https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates ? At least that's in the official docs. Not sure what was in that other link.

/cc @GaneshSPatil might know.

**Comment by GaneshSPatil** [comment]
@arvindsv @ketan  -- IIRC, the `pod-templates` section from the document used to have a link to this example. Hence we picked this up.

But I think it's better to depend on the pod-overview page URL (the one mentioned by @arvindsv), as the content of the page might change, but the link won't :)

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/kubernetes-elastic-agents/pull/112
