### ISSUE TITLE
Passing environment variables to Elastic Agents from templates

### ISSUE THREAD

**Issue by ronalcelaya** [gocd/kubernetes-elastic-agents#184]
Hello guys,

I'm using GO.CD Elastic Agents and everything works fine except for passing environment variables from Templates. 

When passing varibles from Elastic Agent configuration everything works but I would like to pass encrypted variables from my Template definition. Is there a way to pass environment varibles to Elastic Agent Pods from Templates?

Thanks in advance,

Ronal

**Comment by GaneshSPatil** [comment]
Hi @ronalcelaya,

Here we're talking about two different "Environment Variables", the GoCD Environment Variables and the Environment Variables specified to the Pod as Pod Yaml Spec.

In Kubernetes Elastic Agent Plugin Pod Yaml Spec, the Environment Variables are the Kubernetes supported Environment Variables, which will be passed on to the Pod and eventually will be consumed by GoCD Elastic Agent. Hence, we can not specify Encrypted Environment Variables as part of Pod Yaml Spec.


There are following two approaches to pass encrypted environment variables to the Kubernetes Elastic Agent Pod:

#### 1. Using GoCD Environment:

GoCD Environment contains pipelines, agents and environment variables. The environment variables from the environment are passed to the agents. You can create an environment for the pipeline(which requires k8s elastic agent) and then specify the secure environment variable, which will be available to the k8s EA pod. You can find more information about GoCD Environments [here](https://docs.gocd.org/current/configuration/managing_environments.html).

**Note**, _You don't need to specify the GoCD environment to the Kubernetes Elastic Agent. As the pipeline belongs to the environment, all the elastic agents of that pipeline too will be added to the same environment._

#### 2. Using Kubernetes Secrets:

We can use Kubernetes secrets to pass secure values to the pods as environment variables. Know more about it at [kubernetes.io](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/).

**Comment by ronalcelaya** [comment]
Hi @GaneshSPatil 
Thanks for your answer.
 I'm using Kubernetes Secrets and now everything works as expected. Thanks for your help

Best regards
