### ISSUE TITLE
Question: Which rule is the plugin using when it choose the k8s node for the agent?

### ISSUE THREAD

**Issue by faxioman** [gocd/kubernetes-elastic-agents#196]
I'm asking this because all my agent pods are always scheduled on the same worker node.
If I run a pipeline which has a stage with 10 jobs, 10 agent are scheduled on the same worker.

**Comment by GaneshSPatil** [comment]
@faxioman - GoCD Kubernetes Elastic Agent, by default, does not apply any logic when it comes to scheduling elastic agent pod on the cluster nodes. Internally, [kube-scheduler](https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/#:~:text=kube%2Dscheduler,-kube%2Dscheduler%20is&text=The%20scheduler%20finds%20feasible%20Nodes,in%20a%20process%20called%20binding.) would be using the Kubernetes default pod scheduling algorithm to schedule the elastic agent pods.

There are various factors that might be causing the pod to be scheduled on the same node:
1. [Taints and Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#:~:text=Taints%20are%20the%20opposite%20%E2%80%93%20they,not%20scheduled%20onto%20inappropriate%20nodes.)
2. [Node Affinity and anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
3. [Node Selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector)

As most of these are cluster configurations (specifically, node configurations), it's tough to answer why the pods are scheduled on the same worker node. 

We suggest you to take a look at the Kube-Scheduler logs residing at `/var/log/kube-scheduler.log` (on the master node), to understand why the same worker node is always picked to schedule the elastic agent pods.

I'll be closing this ticket for now. Do let us know if you've any further questions.

**Comment by faxioman** [comment]
@GaneshSPatil solved adding request limits to elastic agent profile definition. Could it be useful to add default request limits in pod template?
