### ISSUE TITLE
The pod is interrupted within 100s

### ISSUE THREAD

**Issue by y496237839** [gocd/kubernetes-elastic-agents#302]
After the pipeline is triggered, the pod execution will be term within 100s, and the pod will be regenerated
go-server: 22.1.0
go-agent: 22.1.0
kubernetes-elastic-agents:  Try the following version，3.8.1-284，3.8.2-320，3.7.1-230
![image](https://user-images.githubusercontent.com/19207354/184305452-d68ad1c8-fc19-4eda-adb7-81ccea0b80c1.png)
![image](https://user-images.githubusercontent.com/19207354/184305640-5b6a7eb2-48ae-47ce-8fee-6fdfdf84de20.png)
At present, the command is very simple. There is only  sleep 100. I want to know whether there are parameters that can prolong the lifetime of this pod

**Comment by chadlwilson** [comment]
Sorry, I am not following what you are reporting. Is the job completing as you expect on an elastic agent, or being prematurely terminated and re-scheduled?

It's expected with the current design that after a job is completed, the pod will be terminated, and a new one created for a different job, or for a re-run of the job. But it shouldn't be dying if it is still in the middle of running a job's tasks.

If it's being prematurely terminated, can please look at the k8s API for the pod to see what the reason is for the pod being terminated, and preferably check/share the pod logs as well as the logs from the elastic agent plugin from the GoCD server?

**Comment by y496237839** [comment]
Thanks for your reply,The pod was prematurely terminated and re-scheduled,The task (sleep 100) of this job has not yet been executed completely. I looked at the pod logs and the logs of the elastic agent plugin and didn't find a possible cause. I can't know if the reason for the abnormal termination was k8s or the KubernetesPlugin.
` the elastic agent logs:
2022-08-14 10:37:54,743 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:56 - [Refresh Instances] Syncing k8s elastic agent pod information for cluster PluginSettings{goServerUrl=' ', autoRegisterTimeout=20, maxPendingPods=, clusterUrl=' ', securityToken=' ', clusterCACertData=' ', namespace='devops', autoRegisterPeriod=null}.
2022-08-14 10:37:54,744 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:46 - Using previously created client.
2022-08-14 10:37:54,760 INFO  [165@MessageListener for ServerPingListener] KubernetesPlugin:72 - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.
2022-08-14 10:37:54,760 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:46 - [Server Ping] Deleting Agents: []
2022-08-14 10:37:54,761 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:46 - Using previously created client.
2022-08-14 10:37:54,761 WARN  [165@MessageListener for ServerPingListener] KubernetesPlugin:97 - [Server Ping] Was expecting a containers with IDs [k8s-ea-72370e51-c835-43d4-9dfc-40b1394bc577], but it was missing! Removing missing agents from config.
2022-08-14 10:37:54,761 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:46 - [Server Ping] Disabling Agents: [Agent{agentId='k8s-ea-72370e51-c835-43d4-9dfc-40b1394bc577', agentState='Building', buildState='Building', configState='Enabled'}]
2022-08-14 10:37:54,763 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:46 - [Server Ping] Deleting Agents: [Agent{agentId='k8s-ea-72370e51-c835-43d4-9dfc-40b1394bc577', agentState='Building', buildState='Building', configState='Enabled'}]
2022-08-14 10:37:57,676 DEBUG [160@MessageListener for CreateAgentListener] KubernetesPlugin:46 - [Create Agent] creating elastic agent for profile {PodSpecType=properties, Privileged=true, MaxCPU=4, Environment=, Image=192.168.3.2/base/gocd-agent-docker-jdk8-mvn3-node17:v22.1.0, PodConfiguration=apiVersion: v1
kind: Pod
metadata:
  name: pod-name-prefix-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: {{ GOCD_AGENT_IMAGE }}:{{ LATEST_VERSION }}
      securityContext:
        privileged: true, SpecifiedUsingPodConfiguration=, RemoteFile=, MaxMemory=8G, RemoteFileType=json} in cluster PluginSettings{goServerUrl=' ', autoRegisterTimeout=20, maxPendingPods=, clusterUrl=' ', securityToken=' ', clusterCACertData=' ', namespace='devops', autoRegisterPeriod=null}
2022-08-14 10:37:57,677 DEBUG [160@MessageListener for CreateAgentListener] KubernetesPlugin:56 - [Refresh Instances] Syncing k8s elastic agent pod information for cluster PluginSettings{goServerUrl=' ', autoRegisterTimeout=20, maxPendingPods=, clusterUrl=' ', securityToken=' ', clusterCACertData='', namespace='devops', autoRegisterPeriod=null}.
2022-08-14 10:37:57,677 DEBUG [160@MessageListener for CreateAgentListener] KubernetesPlugin:46 - Using previously created client.
2022-08-14 10:37:57,686 INFO  [160@MessageListener for CreateAgentListener] KubernetesPlugin:72 - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.
2022-08-14 10:37:57,687 DEBUG [160@MessageListener for CreateAgentListener] KubernetesPlugin:46 - Using previously created client.
2022-08-14 10:37:57,687 DEBUG [160@MessageListener for CreateAgentListener] KubernetesPlugin:46 - [Create Agent] Setting memory resource limit on k8s pod: Quantity(amount=8192, format=M, additionalProperties={}).
2022-08-14 10:37:57,687 DEBUG [160@MessageListener for CreateAgentListener] KubernetesPlugin:46 - [Create Agent] Setting cpu resource limit on k8s pod: Quantity(amount=4, format=null, additionalProperties={}).
2022-08-14 10:37:57,687 INFO  [160@MessageListener for CreateAgentListener] KubernetesPlugin:72 - [Create Agent] Creating K8s pod with spec: Pod(apiVersion=v1, kind=Pod, metadata=ObjectMeta(annotations={PodSpecType=properties, Privileged=true, MaxCPU=4, Environment=, Elastic-Agent-Job-Identifier={"pipeline_name":"lawfrontendtest02","pipeline_counter":1,"pipeline_label":"1","stage_name":"stage1","stage_counter":"1","job_name":"build","job_id":329}, Image=192.168.3.2/base/gocd-agent-docker-jdk8-mvn3-node17:v22.1.0, PodConfiguration=apiVersion: v1
kind: Pod
metadata:
  name: pod-name-prefix-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: {{ GOCD_AGENT_IMAGE }}:{{ LATEST_VERSION }}
      securityContext:
        privileged: true, SpecifiedUsingPodConfiguration=, RemoteFile=, MaxMemory=8G, RemoteFileType=json}, clusterName=null, creationTimestamp=2022-08-14T02:37:57Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={Elastic-Agent-Created-By=cd.go.contrib.elasticagent.kubernetes, Elastic-Agent-Job-Id=329, kind=kubernetes-elastic-agent, Elastic-Agent-Environment-Name=mvn}, managedFields=[], name=k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[EnvVar(name=GO_EA_SERVER_URL, value= , valueFrom=null, additionalProperties={}), EnvVar(name=GO_EA_AUTO_REGISTER_KEY, value=8eb37a91-0ef7-41d6-bd58-f3c960559adc, valueFrom=null, additionalProperties={}), EnvVar(name=GO_EA_AUTO_REGISTER_ENVIRONMENT, value=mvn, valueFrom=null, additionalProperties={}), EnvVar(name=GO_EA_AUTO_REGISTER_ELASTIC_AGENT_ID, value=k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a, valueFrom=null, additionalProperties={}), EnvVar(name=GO_EA_AUTO_REGISTER_ELASTIC_PLUGIN_ID, value=cd.go.contrib.elasticagent.kubernetes, valueFrom=null, additionalProperties={})], envFrom=[], image=192.168.3.2/base/gocd-agent-docker-jdk8-mvn3-node17:v22.1.0, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=null, name=k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a, ports=[], readinessProbe=null, resources=ResourceRequirements(limits={memory=Quantity(amount=8589934592, format=null, additionalProperties={}), cpu=Quantity(amount=4, format=null, additionalProperties={})}, requests=null, additionalProperties={}), securityContext=SecurityContext(allowPrivilegeEscalation=null, capabilities=null, privileged=true, procMount=null, readOnlyRootFilesystem=null, runAsGroup=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, windowsOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeDevices=[], volumeMounts=[], workingDir=null, additionalProperties={})], dnsConfig=null, dnsPolicy=null, enableServiceLinks=null, hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector=null, preemptionPolicy=null, priority=null, priorityClassName=null, readinessGates=[], restartPolicy=null, runtimeClassName=null, schedulerName=null, securityContext=null, serviceAccount=null, serviceAccountName=null, shareProcessNamespace=null, subdomain=null, terminationGracePeriodSeconds=null, tolerations=[], volumes=[], additionalProperties={}), status=PodStatus(conditions=[], containerStatuses=[], hostIP=null, initContainerStatuses=[], message=null, nominatedNodeName=null, phase=null, podIP=null, qosClass=null, reason=null, startTime=null, additionalProperties={}), additionalProperties={}).
2022-08-14 10:38:04,677 DEBUG [107@MessageListener for WorkFinder] KubernetesPlugin:46 - [should-assign-work] Job with identifier JobIdentifier{pipelineName='lawfrontendtest02', pipelineCounter=1, pipelineLabel='1', stageName='stage1', stageCounter='1', jobName='build', jobId=329} can be assigned to an agent k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a.
2022-08-14 10:38:54,743 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:56 - [Refresh Instances] Syncing k8s elastic agent pod information for cluster PluginSettings{goServerUrl=' ', autoRegisterTimeout=20, maxPendingPods=, clusterUrl=' ', securityToken=' ', clusterCACertData='', namespace='devops', autoRegisterPeriod=null}.
2022-08-14 10:38:54,743 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:46 - Using previously created client.
2022-08-14 10:38:54,759 INFO  [165@MessageListener for ServerPingListener] KubernetesPlugin:72 - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 1.
2022-08-14 10:38:54,759 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:46 - [Server Ping] Deleting Agents: []
2022-08-14 10:38:54,759 DEBUG [165@MessageListener for ServerPingListener] KubernetesPlugin:46 - Using previously created client.

 the pod logs:
jvm 1    | 2022-08-14 02:38:00,320 INFO  [WrapperJarAppMain] ServerBinaryDownloader:121 - Got server response
jvm 1    | 2022-08-14 02:38:00,416 INFO  [WrapperJarAppMain] ServerBinaryDownloader:129 - Piped the stream to admin/agent
jvm 1    | 2022-08-14 02:38:00,416 INFO  [WrapperJarAppMain] PerfTimer:52 - Performance: Downloading new admin/agent with md5 signature: eabe138e3f243e9613ac370aab80a47c took 102ms
jvm 1    | 2022-08-14 02:38:00,639 INFO  [WrapperJarAppMain] AgentProcessParentImpl:51 - Agent is version: 22.1.0-13913
jvm 1    | 2022-08-14 02:38:00,745 INFO  [WrapperJarAppMain] ServerBinaryDownloader:114 - Downloading agent-plugins.zip
jvm 1    | 2022-08-14 02:38:00,749 INFO  [WrapperJarAppMain] ServerBinaryDownloader:121 - Got server response
jvm 1    | 2022-08-14 02:38:00,798 INFO  [WrapperJarAppMain] ServerBinaryDownloader:129 - Piped the stream to admin/agent-plugins.zip
jvm 1    | 2022-08-14 02:38:00,799 INFO  [WrapperJarAppMain] PerfTimer:52 - Performance: Downloading new admin/agent-plugins.zip with md5 signature: ad4004952ba07c0a4b3fb1732e382aae took 54ms
jvm 1    | 2022-08-14 02:38:00,803 INFO  [WrapperJarAppMain] ServerBinaryDownloader:114 - Downloading tfs-impl.jar
jvm 1    | 2022-08-14 02:38:00,807 INFO  [WrapperJarAppMain] ServerBinaryDownloader:121 - Got server response
jvm 1    | 2022-08-14 02:38:00,871 INFO  [WrapperJarAppMain] ServerBinaryDownloader:129 - Piped the stream to admin/tfs-impl.jar
jvm 1    | 2022-08-14 02:38:00,871 INFO  [WrapperJarAppMain] PerfTimer:52 - Performance: Downloading new admin/tfs-impl.jar with md5 signature: 8c36de6f9628eb159a3a82210061c79b took 68ms
jvm 1    | 2022-08-14 02:38:00,873 INFO  [WrapperJarAppMain] AgentProcessParentImpl:68 - Launching Agent with command: /gocd-jre/bin/java -Xms128m -Xmx256m -Dgo.console.stdout=true -Dgo.console.stdout=true -Dagent.plugins.md5=ad4004952ba07c0a4b3fb1732e382aae -Dagent.binary.md5=eabe138e3f243e9613ac370aab80a47c -Dagent.launcher.md5=1fad7ac3e235ce0b244c8117b88f3568 -Dagent.tfs.md5=8c36de6f9628eb159a3a82210061c79b -Dagent.bootstrapper.version=22.1.0-13913 -jar agent.jar -serverUrl http://10.62.3.92:8153/go -sslVerificationMode FULL
jvm 1    | 2022-08-14 02:38:00,971 [stderr] - [Sun Aug 14 02:38:00 GMT 2022] Starting process: 
jvm 1    | 2022-08-14 02:38:00,972 [stderr] - [Sun Aug 14 02:38:00 GMT 2022]   Working directory    : /go
jvm 1    | 2022-08-14 02:38:00,974 [stderr] - [Sun Aug 14 02:38:00 GMT 2022]   Application arguments: [-serverUrl, http://10.62.3.92:8153/go, -sslVerificationMode, FULL]
jvm 1    | 2022-08-14 02:38:00,974 [stderr] - [Sun Aug 14 02:38:00 GMT 2022]            GoCD Version: 22.1.0-13913
jvm 1    | 2022-08-14 02:38:00,974 [stderr] - [Sun Aug 14 02:38:00 GMT 2022]            Java Version: 17.0.2
jvm 1    | 2022-08-14 02:38:00,974 [stderr] - [Sun Aug 14 02:38:00 GMT 2022]        Operating System: Linux(5.14.15-1.el7.elrepo.x86_64)
jvm 1    | 2022-08-14 02:38:01,424 [stderr] - Could not find file `config/agent-logback.xml'. Attempting to load from classpath.
jvm 1    | 2022-08-14 02:38:01,424 [stderr] - Using classpath resource `jar:onejar:lib/agent-22.1.0-13913-classes.jar!/config/agent-logback.xml'.
jvm 1    | 2022-08-14 02:38:01,563 [stdout] - 2022-08-14 02:38:01,560 INFO  [main] ClassPathXmlApplicationContext:583 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@56620197: startup date [Sun Aug 14 02:38:01 GMT 2022]; root of context hierarchy
jvm 1    | 2022-08-14 02:38:01,593 [stdout] - 2022-08-14 02:38:01,593 INFO  [main] XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [applicationContext.xml]
jvm 1    | 2022-08-14 02:38:01,733 [stdout] - 2022-08-14 02:38:01,733 INFO  [main] XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [applicationContext-plugin-infra.xml]
jvm 1    | 2022-08-14 02:38:01,908 [stdout] - 2022-08-14 02:38:01,907 INFO  [main] DefaultListableBeanFactory:821 - Overriding bean definition for bean 'pluginLoader' with a different definition: replacing [Generic bean: class [com.thoughtworks.go.plugin.infra.PluginLoader]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in URL [jar:onejar:lib/go-plugin-infra-22.1.0-13913.jar!/com/thoughtworks/go/plugin/infra/PluginLoader.class]] with [Generic bean: class [com.thoughtworks.go.plugin.infra.PluginLoader]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [applicationContext-plugin-infra.xml]]
jvm 1    | 2022-08-14 02:38:02,073 [stdout] - 2022-08-14 02:38:02,072 INFO  [main] AutowiredAnnotationBeanPostProcessor:156 - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
jvm 1    | 2022-08-14 02:38:02,970 [stdout] - 2022-08-14 02:38:02,968 INFO  [main] AgentStatusHttpd:90 - Agent status HTTP API server running on http://localhost:8152.
jvm 1    | 2022-08-14 02:38:03,062 [stdout] - 2022-08-14 02:38:03,062 INFO  [main] AgentHTTPClientController:96 - Configured remoting type: RemotingClient
jvm 1    | 2022-08-14 02:38:03,077 [stdout] - 2022-08-14 02:38:03,077 INFO  [main] ThreadPoolTaskScheduler:166 - Initializing ExecutorService 'scheduler'
jvm 1    | 2022-08-14 02:38:03,517 [stdout] - 2022-08-14 02:38:03,516 INFO  [main] DefaultPluginJarChangeListener:67 - Plugin load starting: /go/plugins/bundled/gocd-yum-repository-poller-plugin.jar
jvm 1    | 2022-08-14 02:38:03,672 [stdout] - 2022-08-14 02:38:03,672 INFO  [main] DefaultPluginJarChangeListener:74 - Plugin load finished: /go/plugins/bundled/gocd-yum-repository-poller-plugin.jar
jvm 1    | 2022-08-14 02:38:03,682 [stdout] - 2022-08-14 02:38:03,681 INFO  [main] DefaultPluginJarChangeListener:67 - Plugin load starting: /go/plugins/external/docker-task-assembly-0.1.27.jar
jvm 1    | 2022-08-14 02:38:03,919 [stdout] - 2022-08-14 02:38:03,918 INFO  [main] DefaultPluginJarChangeListener:74 - Plugin load finished: /go/plugins/external/docker-task-assembly-0.1.27.jar
jvm 1    | 2022-08-14 02:38:03,928 [stdout] - 2022-08-14 02:38:03,928 INFO  [main] DefaultPluginJarChangeListener:67 - Plugin load starting: /go/plugins/external/gocd-docker-pipeline-plugin-1.0.0.jar
jvm 1    | 2022-08-14 02:38:04,161 [stdout] - 2022-08-14 02:38:04,161 INFO  [scheduler-1] SslInfrastructureService:78 - [Agent Registration] Starting to register agent.
jvm 1    | 2022-08-14 02:38:04,161 [stdout] - 2022-08-14 02:38:04,161 INFO  [scheduler-1] SslInfrastructureService:88 - [Agent Registration] Fetching token from server.
jvm 1    | 2022-08-14 02:38:04,176 [stdout] - 2022-08-14 02:38:04,175 INFO  [scheduler-1] TokenRequester:56 - The server has generated token for the agent.
jvm 1    | 2022-08-14 02:38:04,177 [stdout] - 2022-08-14 02:38:04,176 INFO  [scheduler-1] SslInfrastructureService:91 - [Agent Registration] Got a token from server.
jvm 1    | 2022-08-14 02:38:04,185 [stdout] - 2022-08-14 02:38:04,184 INFO  [scheduler-1] SslInfrastructureService:170 - This agent is now approved by the server.
jvm 1    | 2022-08-14 02:38:04,185 [stdout] - 2022-08-14 02:38:04,185 INFO  [scheduler-1] SslInfrastructureService:119 - [Agent Registration] Retrieved registration from Go server.
jvm 1    | 2022-08-14 02:38:04,217 [stdout] - 2022-08-14 02:38:04,216 INFO  [scheduler-1] SslInfrastructureService:81 - [Agent Registration] Successfully registered agent.
jvm 1    | 2022-08-14 02:38:04,301 [stdout] - 2022-08-14 02:38:04,301 INFO  [main] DefaultPluginJarChangeListener:74 - Plugin load finished: /go/plugins/external/gocd-docker-pipeline-plugin-1.0.0.jar
jvm 1    | 2022-08-14 02:38:04,310 [stdout] - 2022-08-14 02:38:04,310 INFO  [main] DefaultPluginJarChangeListener:67 - Plugin load starting: /go/plugins/external/script-executor-1.0.1.jar
jvm 1    | 2022-08-14 02:38:04,645 [stdout] - 2022-08-14 02:38:04,645 ERROR [scheduler-2] RemotingClient:166 - Server responded to action `ping` with: status[422 Unprocessable Entity], body[{
jvm 1    | 2022-08-14 02:38:04,645 [stdout] -   "message" : "Agent [Agent [k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a, 10.96.5.198, 0c5f489f-e16d-4aa8-8fed-cb8ed5ea53e4, null]] has no cookie set; nested exception is com.thoughtworks.go.server.service.AgentNoCookieSetException: Agent [Agent [k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a, 10.96.5.198, 0c5f489f-e16d-4aa8-8fed-cb8ed5ea53e4, null]] has no cookie set"
jvm 1    | 2022-08-14 02:38:04,646 [stdout] - }]
jvm 1    | 2022-08-14 02:38:04,647 [stdout] - 2022-08-14 02:38:04,647 ERROR [scheduler-2] AgentHTTPClientController:114 - Error occurred when agent tried to ping server: 
jvm 1    | 2022-08-14 02:38:04,647 [stdout] - java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: The server returned status code 422. Possible reasons include:
jvm 1    | 2022-08-14 02:38:04,647 [stdout] -    - This agent has been deleted from the configuration
jvm 1    | 2022-08-14 02:38:04,647 [stdout] -    - This agent is pending approval
jvm 1    | 2022-08-14 02:38:04,647 [stdout] -    - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/22.1.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at com.thoughtworks.go.agent.RemotingClient.post(RemotingClient.java:118)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at com.thoughtworks.go.agent.RemotingClient.ping(RemotingClient.java:74)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at com.thoughtworks.go.agent.AgentHTTPClientController.ping(AgentHTTPClientController.java:109)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - Caused by: org.apache.http.client.ClientProtocolException: The server returned status code 422. Possible reasons include:
jvm 1    | 2022-08-14 02:38:04,648 [stdout] -    - This agent has been deleted from the configuration
jvm 1    | 2022-08-14 02:38:04,648 [stdout] -    - This agent is pending approval
jvm 1    | 2022-08-14 02:38:04,648 [stdout] -    - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/22.1.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at com.thoughtworks.go.agent.RemotingClient.validateResponse(RemotingClient.java:141)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	at com.thoughtworks.go.agent.RemotingClient.post(RemotingClient.java:114)
jvm 1    | 2022-08-14 02:38:04,648 [stdout] - 	... 14 common frames omitted
jvm 1    | 2022-08-14 02:38:04,666 [stdout] - 2022-08-14 02:38:04,666 INFO  [main] DefaultPluginJarChangeListener:74 - Plugin load finished: /go/plugins/external/script-executor-1.0.1.jar
jvm 1    | 2022-08-14 02:38:04,666 [stdout] - 2022-08-14 02:38:04,666 INFO  [scheduler-1] AgentHTTPClientController:139 - About to get cookie from the server.
jvm 1    | 2022-08-14 02:38:04,673 [stdout] - 2022-08-14 02:38:04,673 INFO  [scheduler-1] AgentHTTPClientController:142 - Got cookie: 2b4d0ee5-80cc-4277-b251-2df714abec84
jvm 1    | 2022-08-14 02:38:14,762 [stdout] - 2022-08-14 02:38:14,761 INFO  [scheduler-2] HttpService:125 - Got back 200 from server
jvm 1    | 2022-08-14 02:38:14,763 [stdout] - 2022-08-14 02:38:14,762 INFO  [scheduler-2] DefaultGoPublisher:88 - Agent [k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a, 10.96.5.198, 0c5f489f-e16d-4aa8-8fed-cb8ed5ea53e4] is reporting status [Preparing] to Go Server for Build [lawfrontendtest02/1/stage1/1/build/329]
jvm 1    | 2022-08-14 02:38:17,010 [stdout] - 2022-08-14 02:38:17,009 INFO  [scheduler-2] HttpService:125 - Got back 200 from server
jvm 1    | 2022-08-14 02:38:17,010 [stdout] - 2022-08-14 02:38:17,010 INFO  [scheduler-2] DefaultGoPublisher:88 - Agent [k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a, 10.96.5.198, 0c5f489f-e16d-4aa8-8fed-cb8ed5ea53e4] is reporting status [Building] to Go Server for Build [lawfrontendtest02/1/stage1/1/build/329]
jvm 1    | 2022-08-14 02:38:17,021 [stdout] - 2022-08-14 02:38:17,020 INFO  [scheduler-2] CommandLine:318 - Running command: sleep 110
jvm 1    | 2022-08-14 02:38:24,758 [stdout] - 2022-08-14 02:38:24,757 INFO  [pool-2-thread-1] HttpService:125 - Got back 200 from server
wrapper  | TERM trapped.  Shutting down.

![image](https://user-images.githubusercontent.com/19207354/184521208-82b991e6-dca4-4c65-aaad-4d1fc5a04755.png)

![image](https://user-images.githubusercontent.com/19207354/184521226-661b06a0-7895-4585-b35d-ac1527b87d57.png)

`

**Comment by chadlwilson** [comment]
The final `wrapper  | TERM trapped.  Shutting down.` implies Kubernetes sent a kill signal to the pod. That might be because the plugin deleted the pod, or because it failed health check and was being restarted. It looks like the plugin is deleting the pod/agent because it has lost registration, however the logs you have attached seem to be missing the full time period for the two pods mentioned there.

For `k8s-ea-72370e51-c835-43d4-9dfc-40b1394bc577` the pod logs aren't included so not sure how the times line up. Looks like the pod logs are from the second pod. It does say at one point `Was expecting a containers with IDs [k8s-ea-72370e51-c835-43d4-9dfc-40b1394bc577], but it was missing! Removing missing agents from config` which implies the plugin might be deleting the pod because its not registered with the server for some reason.

For `k8s-ea-7e4f7c8c-e6de-44e8-861b-1c5e8ea56b1a` the elastic agent plugin logs are missing the end part when the pod is deleted, so cannot confirm it had the same behaviour as the first.

Can I suggest it would help if you tried to build a timeline of what happened at exactly which timestamps, to ensure enough information is being included?

Perhaps try and look at the server log to find logs or errors relating to registration of the agent. For some reason it seems the GoCD Server things the agent is not there anymore so it is deleting the pod. you might want to check that the token for the service account you are using has all the correct permissions noted at https://github.com/gocd/kubernetes-elastic-agents/blob/master/docs/configure_cluster_profile.md#configure-cluster-profile

**Comment by y496237839** [comment]
thank you!
According to your suggestions and documents, it restored normal after re granting service account permissions.
![image](https://user-images.githubusercontent.com/19207354/184623036-ba97c248-99cf-4e97-bdd4-75118e5aba46.png)

**Comment by chadlwilson** [comment]
Thanks! It's a bit unfortunately that it didn't seem to log any errors due to the missing permissions. My guess is that it didn't have the right `list` permissions or something like that :-/
