### ISSUE TITLE
If using a non-default namespace, GoCD is unable to render the status report page

### ISSUE THREAD

**Issue by brandonvin** [gocd/kubernetes-elastic-agents#319]
I followed the docs to set up the plugin, and chose to use a non-default namespace, `gocd`, to isolate GoCD from other users of the Kubernetes cluster. The GoCD server was able to run pipelines just fine, but I discovered that the status reports for the cluster and agents on the Elastic Agent Configurations page weren't able to render. Instead, they returned error pages with the following:

When opening the cluster status report:

> Failure executing: GET at: https://.../api/v1/nodes. Message: nodes is forbidden: User "system:serviceaccount:gocd:gocd-server" cannot list resource "nodes" in API group "" at the cluster scope. ...

When clicking on a single agent:

> Failure executing: GET at: https://.../api/v1/events. Message: events is forbidden: User “system:serviceaccount:gocd:gocd-server” cannot list resource “events” in API group “” at the cluster scope. ...

In order to fix these, I added the following permissions at the cluster scope to the GoCD server's service account:
- nodes: list
- events: list

In hindsight, now that I know a little more about Kubernetes, it makes sense that nodes permission needs to be at the cluster scope because nodes are not namespaced resources.

This may just be a matter of updating documentation to specify which of the permissions need to be at the namespace scope, which need to be at the cluster scope (and maybe which need to be at both scopes).

https://github.com/gocd/kubernetes-elastic-agents/blob/06988fcbe87bd6e3a9c0b54eb49c60e01c2966fa/docs/configure_cluster_profile.md

**Comment by chadlwilson** [comment]
Yeah, the docs aren't so specific about how you should go about generating this token.

The helm chart which preconfigures for this when RBAC is enabled is a decent reference in the meantime:
https://github.com/gocd/helm-chart/blob/master/gocd/templates/gocd-ea-cluster-role.yaml
https://github.com/gocd/helm-chart/blob/master/gocd/templates/gocd-ea-cluster-role-binding.yaml
