### ISSUE TITLE
After the gocd db data is migrated, the following error message is displayed:

### ISSUE THREAD

**Issue by peter-zxh** [gocd/kubernetes-elastic-agents#320]
Perform data backup as described in admin backup, and migrate the data to the new gocd environment. Click plugin-cd.go.contrib.elasticagent.kubernetes The following error is reported in the log file. It is found that the cruise.h2.db database using the new gocd is normal, but there will be problems using the migrated cruise.h2.db file. Please help me

The log is as follows, please help analyze：
2022-11-23 03:15:09,988 ERROR [101@MessageListener for WorkFinder] KubernetesPlugin:127 - Failed to handle request cd.go.elastic-agent.should-assign-work
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [A namespace name]  failed.
[...]
com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
[....]
Caused by: java.net.SocketTimeoutException: connect timed out

**Comment by chadlwilson** [comment]
Please supply more information, e.g
- what type of migrate or upgrade you performed
- which versions of GoCD and plugins you were using before and after
- what you have done to try and debug or fix the issue

This doesn't sound related to database change, but may relate to the upgrade you performed or just your new environment. This indicates the plugin cannot talk to your cluster's API server. Try comparing the config for the cluster profile before and after to check the cluster URL/token/cluster CA cert is correct for the new environment. If you are trying to load the config in a new cluster, you will need to correct the configuration for the new cluster in your elastic agents configuration at the very least.

**Comment by peter-zxh** [comment]
1. The gocd image and plug-in version after migration are consistent with those before migration (gocd==19.5.0, plug-in version==3.0.0-156)
2. I found that the problem was not cluster URL/token/cluster CA certificate, because the plug-in can call the cluster api to create the pod of go agent
3. What places do you need to configure to load the configuration in the new cluster? I have configured the k8s cluster profile and Elastic Agent Profiles under the administrative profiles of GOCD. Is there anything else you need to configure?

**Comment by chadlwilson** [comment]
The error above says 'connect timed out' which would indicate a connectivity issue calling the API server so I don't understand what problem you are having if you say it can create pods successfully.

**Comment by chadlwilson** [comment]
Other than that what is different about your new clusterr to the old cluster? Which k8s version? These are very old versions you are dealing with. No guarantees they work on new k8s and docker.

**Comment by chadlwilson** [comment]
Closing this for now - if you can supply additional info we can re-open it.
