### ISSUE TITLE
Incorrect credentials being used when creating Kubernetes Client

### ISSUE THREAD

**Issue by JamesMcNee** [gocd/kubernetes-elastic-agents#347]
Hello,

We are seeing an issue when going from version `v3.8.2-350` of the plugin to `v3.8.4-408` where intermittently the 'wrong' cluster credentials are being used when pods are being created. The credentials that are being used are that of the GoCD server rather than the ones that have been created specifically for the agents. We know this as we see an error message like below (some info redacted).

```
Failed to create agent pod: Failure executing: POST at: https://<ip-addr>/api/v1/namespaces/gocd-agents/pods. 

Message: Forbidden! Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: 

User "<gocd-server-service-account>" cannot create resource "pods" in API group "" in the namespace "gocd-agents".
```

Doing some digging in the [changes between these two versions](https://github.com/gocd/kubernetes-elastic-agents/compare/v3.8.2-350...v3.8.4-408) I think the issue is due to [an upgrade of the underlying Kubernetes client](https://github.com/gocd/kubernetes-elastic-agents/commit/e641fc91976e3e00e919866bfed67306246c5f53) from version `5.12.2` to `5.12.4`.

Between these versions, they have [back-ported some functionality](https://github.com/fabric8io/kubernetes-client/commit/029b085ff5badcf1abb8d9d50949ecbe3527033b) to automatically 'refresh' tokens, which is [utilising the well known locations](https://github.com/fabric8io/kubernetes-client/blob/f63fa5faf65787ee31841ce5f9d93ccb8af31280/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L356-L466) for these credentials. The issue is, that this is picking up the credentials for the server, rather than those that should be being used for the agent which is passed into the plugin.

Given a cursory glance I could not find a way to disable this auto refresh mechanism, but I have far from done a deep dive.

**Comment by chadlwilson** [comment]
Thanks for the digging - yikes, this sounds no good.

What are the requirements to replicate this?
- GoCD server running inside kubernetes itself
- GoCD server with service account of its own
- Plugin cluster profile configured to use a service account token linked to a different service account to the server?

Any other requirements in terms of Kubernetes versions etc?

**Comment by JamesMcNee** [comment]
Hi @chadlwilson -- Thanks for getting back so quickly! Indeed, no good!

Those requirements that you list are correct and all that I can think of to replicate this behaviour; Kubernetes version should be irrelevant for replicating. 

Something I forgot to clarify in the above post, I said 'intermittently' using the incorrect credentials -- My belief is that this is due to the refresh occurring every 1 minute and the clients being recycled every 10 by the plugin. So there are periods (e.g. when the server first starts the plugin initialises) where it is within the first minute and therefore skips the refresh.

**Comment by chadlwilson** [comment]
Sure, a PR is welcome. Would need to understand if that's the best way or we are better to turn off autoconfiguration entirely as it seems some others did from that thread?

**Comment by JamesMcNee** [comment]
Unfortunately neither of the suggestions on that issue worked 😞 

Current theory is that they only work with the latest version (6.x) and not with the backports to 5.x, but I have not yet validated this.

**Comment by JamesMcNee** [comment]
Hey @chadlwilson Have raised a PR updating to use the latest version of the `kubernetes-client`

Tested both disabling auto configuration completely when using this version and using the token provider, both work, but went with disabling auto configure.

Verified against our development GoCD server.
