### ISSUE TITLE
Elastic agents fails to spin up in EKS version 1.29

### ISSUE THREAD

**Issue by andcri** [gocd/kubernetes-elastic-agents#400]
Hello,
I m using the latest version of the chart with the latest elastic agent plugin, everything works fine on my eks 1.25 cluster but the same configuration doesnt seem to work on version 1.29. Specifically the agents are not getting created whenever a job starts and I m getting this logs from the UI

![image](https://github.com/gocd/helm-chart/assets/52462858/cd78ec55-ad92-41db-b19f-03bc129605d7)

From the logs of the server I m getting this:

![image](https://github.com/gocd/helm-chart/assets/52462858/1bdb4f38-39fc-44a4-a768-ec31a16ab51d)
 
but from previous closed issues I saw that this message could be safely ignored.

Is this an incompatibility with k8s versions > 1.25 or is there any extra configuration needed that wasnt required before? Thanks.

**Comment by chadlwilson** [comment]
Did you ever figure out where the slowness was coming from here?
