### ISSUE TITLE
Support for multiple clusters

### ISSUE THREAD

**Issue by joaoubaldo** [gocd/kubernetes-elastic-agents#43]
I have a scenario where I need different gocd agents for different environments due to networking policies (as in, qa agents only see qa resources, same for staging and production). Is support for multiple clusters planned? Is there any way to support this scenario with the current plugin version?

**Comment by varshavaradarajan** [comment]
@joaoubaldo - with the current plugin version, there isn't. I was thinking whether we could have the cluster information in the elastic agent profile in GoCD so that we can have different profiles pointing to different clusters. This is useful if people have clusters set up on multiple platforms. I think a use case for it could be to test a k8s deployment on different platforms. @akshaydewan, @arvindsv , @bdpiparva , @GaneshSPatil - WDYT?

**Comment by varshavaradarajan** [comment]
Yeah - similar to how we did it with ecs elastic agent. Some properties can be overridden at the elastic agent profile level.

**Comment by joaoubaldo** [comment]
That sounds good. I will keep an eye on this, thanks.

**Comment by cfontes** [comment]
I am also very interested on this feature.

I am running GoCD on one cluster that deploys to several other clusters. Right now testing is a bit hard as my test containers from the devops cluster need to have a direct network (and firewall rules/ routes etc..) connection to all clusters, which is not the most secure approach.

The ideal would be to have the test container running in the cluster it will be testing itself.

**Comment by arvindsv** [comment]
@cfontes I see that the elastic agent profile is being updated with some more settings in [this pull request #60](https://github.com/gocd/kubernetes-elastic-agents/pull/60).

@GaneshSPatil @sheroy Is that the right place to add support for a different cluster? Or, does it need more information such as credentials, etc.

**Comment by saifally** [comment]
@arvindsv . In my opinion that is the right place. I will be adding that as part of #60 . I have the credentials and all details at the elastic profile level. I have to add the front end code to capture Clutser Url and CA. However , first thing first, I have to fix some the review comments from @GaneshSPatil  first.

**Comment by cfontes** [comment]
@arvindsv and @saifally 

Great, thanks, I will be following this PR.

**Comment by wstewartii** [comment]
Any update on this?

**Comment by bdpiparva** [comment]
@wstewartii - We are working to support multi-cluster for the elastic agent plugin in the upcoming release. See issue https://github.com/gocd/gocd/issues/5538 for more information. The plugin will be updated as well, to support the same.

**Comment by varshavaradarajan** [comment]
With the release of GoCD 19.3.0 and the latest k8s plugin, multi cluster support has been added. This issue can now be closed.

cc @GaneshSPatil
