### ISSUE TITLE
Use smarter defaults when server runs in Kubernetes as well

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/kubernetes-elastic-agents#44]
If go.cd server itself runs in Kubernetes a number of currently configurable fields can be set in a smarter way.

**Cluster URL**
Either use `https://kubernetes.default.svc.cluster.local` or `https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}` by default

**Token**
Default to loading from` /var/run/secrets/kubernetes.io/serviceaccount/token`

**Ca.crt**
Default to loading from `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

**Namespace**
Default to loading from `/var/run/secrets/kubernetes.io/serviceaccount/namespace` to run them in the same namespaces as the server

**Comment by chadlwilson** [comment]
This is now the default behavior with [v4.0.0-505](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v4.0.0-505), especially when using with the GoCD Helm chart which already configures a valid service account for the "normal" case. Also will handle picking up a new token value from the disk after expiry/refresh.
