### ISSUE TITLE
Performance impact of K8s plugin on the Go Server

### ISSUE THREAD

**Issue by rajiesh** [gocd/kubernetes-elastic-agents#46]
During the performance run benchmarking on latest physical hardware, it was noticed that having K8s Elastic agent plugin used in the setup for performance test the time between a job moving from `scheduled` to `assigned` is increased.

Configuration of performance environment **WITHOUT** K8s:

Go Version : 18.2.0 and 18.3.0
Total pipelines: 1000
Pipelines run on static agents: 750
Pipelines run on ECS elastic agents: 250
Number of Static agents: 70
Server Max Mem: 10g
Server Min mem: 8g
Max EC2 instances: 4 c3.2xlarge

With this setup when the performance run was done for 12 hour period the **average time for job instance to move from`scheduled` to `assgined` was about a minute**. So total run of each pipelines were approximately 200

Configuration of performance environment **WITH** K8s:

Go Version : 18.2.0 and 18.3.0
K8s Elastic agent version: 1.0.0-94
Total pipelines: 1100
Pipelines run on static agents: 750
Pipelines run on ECS elastic agents: 250
Pipelines run on K8s elastic agents: 100
Number of Static agents: 70
Server Max Mem: 10g
Server Min mem: 8g
Max EC2 instances: 4 c3.2xlarge
K8s Cluster nodes: 3 nodes with 4vCPU and 15GB memory

With this setup when the performance run was done for 12 hour period the **average time for job instance to move from`scheduled` to `assgined` was about 10 minutes**. So total run of each pipelines were approximately only 80

Why there is a increase in delay for job instances to move from `scheduled` to `assigned` need to be investigated.

More data are captured on the server box(db backup, logs). Whoever is picking this issue, please message me, can pair to look into the captured data

**Comment by chadlwilson** [comment]
This is not relevant now since EAv3 and lots of work on agent start and work pick-up speed done in GoCD core. Closing for now :-)
