### ISSUE TITLE
Agent auto-register timeout at Elastic Agent Profiles level

### ISSUE THREAD

**Issue by saifally** [gocd/kubernetes-elastic-agents#52]
Hi Guys

Thank you for the awesome plugin.
Can I request a feature - for having the Agent auto-register timeout  
at Elastic Agent Profiles.
We are planning to have different agents - java, node ,Golang etc
and each of the agents could have different up time.

I can contribute if needed

Thanks
Saif

**Comment by varshavaradarajan** [comment]
@saifally - I think you mean the timeout before which the agent is killed. That's what I understood from up time. Do you mind telling why you require different up times for these? Each elastic agent that comes up, even if it stays idle, without dying, it won't be used for the next job.

**Comment by saifally** [comment]
Yes, that what I meant. 
Our requirement is to have different type of agents - some for build - java code compile etc,some for integration tests that would have longer up time. The agents and their pods are up until this timeout is reached  and that reduces the capacity on the kubernetes cluster

**Comment by chadlwilson** [comment]
This is not relevant with single-shot agents in EAv3. To reconsider relevance when/if agent reuse is introduced, e.g via https://github.com/gocd/kubernetes-elastic-agents/pull/355
