### ISSUE TITLE
Agent Status Fails If Pod Contains Multiple Containers

### ISSUE THREAD

**Issue by Evesy** [gocd/kubernetes-elastic-agents#58]
Hi,

We're using Elastic agents and the pod spec we use has multiple containers within them. This causes the 'Agent Status' page to break as the plugin is unable to retrieve logs etc. from the pod as it does not specify a given container:

```
Failure executing: GET at: https://<>/api/v1/namespaces/gocd/pods/gocd-admin-agent-8e18234c-d4f2-49f6-b389-646bb1572bd3/log?pretty=true. Message: a container name must be specified for pod gocd-admin-agent-8e18234c-d4f2-49f6-b389-646bb1572bd3, choose one of: [gocd-agent docker]. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=a container name must be specified for pod gocd-admin-agent-8e18234c-d4f2-49f6-b389-646bb1572bd3, choose one of: [gocd-agent docker], metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
```

This just affects the status report for individual jobs (i.e. `https://<>/go/admin/status_reports/cd.go.contrib.elasticagent.kubernetes/gocd-admin-agent-8e18234c-d4f2-49f6-b389-646bb1572bd3`)

Would it be within scope to provide an option to specify the _master_ container or something to that affect?

**Comment by bdpiparva** [comment]
@Evesy -- Are all the container in a pod is gocd-agents?

**Comment by Evesy** [comment]
@bdpiparva One container is the running GoCD agent (`gocd-agent`), the other contains a Docker runtime (`docker`)

**Comment by bdpiparva** [comment]
@Evesy -- Plugin always expects only one container running in a pod which is the GoCD agent. 

https://github.com/gocd/kubernetes-elastic-agents/blob/63ef5611de5ee583f93384491522629b25bc798b/src/main/java/cd/go/contrib/elasticagent/model/reports/agent/KubernetesElasticAgent.java#L41-L53

Do you mind submitting PR to fix the issue?

**Comment by sgran** [comment]
@bdpiparva there is a PR open now.
