### ISSUE TITLE
Display Job Information associated with pod on status report page

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/kubernetes-elastic-agents#6]
* Status Report should include JobIdentifier information:
    - [ ] Container building job.
           - Each container row should also include the information about the building job.
    - [ ] Link to build_details_page
           - The job identifier field from the container row should link to the build_details_page of the current job.
    - [ ] Highlight Pod-Job Relation
           - When a user navigates from `build_details_page` to `status_report_page`, the report should highlight the pod which is building the current job. (more information:https://github.com/gocd/gocd/issues/4091#issuecomment-352979314 )

**Comment by bdpiparva** [comment]
Closing since it is not relevant. Now we have separate call to show agent status report.
