### ISSUE TITLE
In version 2.0.0 console log is often lost. 

### ISSUE THREAD

**Issue by aamattos** [gocd/kubernetes-elastic-agents#64]
After update to plugin v 2.0.0 (with gocd 18.10) consolo output is often lost or truncated

**Comment by bdpiparva** [comment]
@aamattos - There isn't much change between the previous version of the plugin and 2.0.0. Please, can you provide more information on the same?

**Comment by aamattos** [comment]
Hi @bdpiparva, I'm using Elastic Agents with Kubernetes (Openshift) and Centos7 Agents.
With version 2.0.0 of the plugin, it appears than whenever a job fail, the console output is empty or truncated.
I rolled back to version 1.0.1-107 and everything was fine again.

**Comment by bdpiparva** [comment]
@aamattos - According to https://github.com/gocd/kubernetes-elastic-agents/compare/v1.0.1..v2.0.0 I don't see any changes in the library or major change in the plugin. Please can you provide more information about the kubernetes environment to reproduce the issue locally?

**Comment by aamattos** [comment]
According to the release notes of version 2.0.0 : "Added support to terminate pod once job is finished."
I noticed that now agents are immediately killed after job completion (which is great :)).
The problem,I think, is that GoCd has troubles retrieving the job log.

**Comment by odays** [comment]
I am seeing a similar issue to this in a very similar set up. Using version 2 of plugin to talk to an OpenShift cluster, I am not able to see any output in console.log at all, regardless of pass or failure.

Rolled back to the previous version and now seeing the logs. This is with openshift origin 3.11 and gocd 18.10.

**Comment by adityasood** [comment]
We have identified the issue which was causing the partial or no logs being updated. We are working on a fix and will update the issue with the progress.

**Comment by bdpiparva** [comment]
Closing this as it is a general issue with agent console log reporting. Please watch the progress of the issue at https://github.com/gocd/gocd/issues/5322

**Comment by maheshp** [comment]
Fixed in GoCD core as part of https://github.com/gocd/gocd/pull/5335
