### ISSUE TITLE
KeyUsage does not allow digital signatures

### ISSUE THREAD

**Issue by myownsoul** [gocd/kubernetes-elastic-agents#67]
Hi guys:

Currently, we met a problem cause configure the Elastic Agent Plugin failed.

# Environment
- SLES 12 SP4
- Kubernetes v1.11.2
- GoCD Server URL: `https://172.21.3.147:8514`
- K8S API Server URL: `https://172.21.3.147:6443`

# Deployment 
- GoCD v18.10.0
- GoCD Server has been deployed by using RPMs
- GoCD Agent has been deployed by using GoCD helm chars（agent only mode）

# GoCD Agent Deployments
## ServiceAccount
```
# kubectl get sa -n gocd
NAME       SECRETS   AGE
default    1         1h
gocd-app   1         1h
```

## ClusterRole
```
# kubectl get clusterrole gocd-app -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: 2018-11-20T06:13:45Z
  labels:
    app: gocd
    chart: gocd-1.5.5
    heritage: Tiller
    release: gocd-app
  name: gocd-app
  resourceVersion: "16937324"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/gocd-app
  uid: 6f97d2af-ec8b-11e8-b41c-0017fa00e2a6
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
```

## ClusterRoleBinding
```
# kubectl get clusterrolebinding gocd-app -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: 2018-11-20T06:13:45Z
  labels:
    app: gocd
    chart: gocd-1.5.5
    heritage: Tiller
    release: gocd-app
  name: gocd-app
  resourceVersion: "16937326"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/gocd-app
  uid: 6f9af79a-ec8b-11e8-b41c-0017fa00e2a6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gocd-app
subjects:
- kind: ServiceAccount
  name: gocd-app
  namespace: gocd
```

## Deployments
```
# kubectl get all -n gocd
NAME                             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/gocd-app-agent   0         0         0            0           1h

NAME                                        DESIRED   CURRENT   READY     AGE
replicaset.apps/gocd-app-agent-6f7cf7744b   0         0         0         1h
```

# Logs

```
2018-11-20 07:35:35,951 ERROR [qtp1166807841-31] KubernetesPlugin:128 - Failed validation of plugin settings. The reasons could be - Cluster Url is configured incorrectly or the service account token might not have enough permissions to list namespaces or incorrect CA certificate.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
.
.
.

Caused by: sun.security.validator.ValidatorException: KeyUsage does not allow digital signatures
	at sun.security.validator.EndEntityChecker.checkTLSServer(EndEntityChecker.java:271)
	at sun.security.validator.EndEntityChecker.check(EndEntityChecker.java:143)
	at sun.security.validator.Validator.validate(Validator.java:274)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 566 common frames omitted
```

Any idea about this issue?

Thanks in advance.

**Comment by varshavaradarajan** [comment]
@myownsoul - you mentioned that the server has been  deployed by using RPMs. So, its not on the k8s cluster? The agents are created using the agent only mode, which brings up static agents on the k8s cluster. So, why are you configuring the k8s elastic agent plugin? 

If you also need elastic agents, can you please share the plugin configuration that you have done manually?

**Comment by myownsoul** [comment]
@varshavaradarajan 
Yes.GoCD server are not deployed on k8s cluster. We use k8s elastic agent plugin to implement the go-server manage the go-agent running on k8s cluster due to we do not have much VMs to deploy go-agent.

For the plugin configuration, please help to check the below 2 pictures.
https://github.com/myownsoul/learngit/blob/master/plugin-config-01.png
https://github.com/myownsoul/learngit/blob/master/plugin-config-02.png

Thanks a lot.

**Comment by varshavaradarajan** [comment]
How did you obtain the CA cert? From the logs, it looks like the the certificate issued by the CA for the cluster is different from the one being specified in the plugin settings. 

Usually the CA certificate can be obtained by doing - 

```
kubectl get secret <secret_name> --namespace=<namespace> -o jsonpath="{.data['ca\.crt']}" | base64 --decode
```

**Comment by myownsoul** [comment]
@varshavaradarajan 

I used the command to get token and CA cert as below:

```
    The service account called gocd in namespace gocd has been associated with the role. To check,
        secret_name=$(kubectl get serviceaccount gocd --namespace=gocd  -o jsonpath="{.secrets[0].name}")
        kubectl get secret $secret_name --namespace=gocd -o jsonpath="{.data['token']}" | base64 --decode

    To obtain the CA certificate, do
        kubectl get secret $secret_name --namespace=gocd  -o jsonpath="{.data['ca\.crt']}" | base64 --decode
```

**Comment by myownsoul** [comment]
@varshavaradarajan 

Do you know how to deal with the end-of-line of CA certification ?

I just copy and paste the CA content without the first line(-----BEGIN CERTIFICATE-----) and last line(-----END CERTIFICATE-----).

As below:

https://github.com/myownsoul/learngit/blob/master/plugin-config-03.png

**Comment by varshavaradarajan** [comment]
You can paste it as is as indicated by the help text below in your screenshot.

**Comment by myownsoul** [comment]
@varshavaradarajan 
Yes, I've pasted it as the help text mentioned, but the problem still exist. :(

**Comment by ketan** [comment]
Hi —

It's currently thanksgiving and a bunch of folks are unavailable to look at this issue. Someone will look at this next week and respond.

**Comment by myownsoul** [comment]
Hi all, the problem has been sloved.  I re-created k8s component cert as the below keyUsage: 

```
kind	        Key usage
server	digital signature, key encipherment, server auth
client	digital signature, key encipherment, client auth
```

Below is the detailed link from k8s official documents.
https://kubernetes.io/docs/setup/certificates/

@varshavaradarajan  
Thanks for your greate help, it's not a GoCD elastic agent plugin issue and can be closed.

**Comment by arvindsv** [comment]
@myownsoul Thank you for following up. Closing this now.
