### ISSUE TITLE
Provide an option to download a pod spec from a repository

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/kubernetes-elastic-agents#78]
Currently, the pod spec that one can configure for the k8s elastic agent profile is done using the text area. If an option to download the pod yaml (or json) from another location is provided, then users may use a pod spec that's been checked in somewhere. The reason someone would want to check in the pod spec is the same as having pipelines in config repos. Although, it might seem that the pod spec is not likely to change as often as  pipelines that is needs versioning, this can still be useful especially when a platform supporting k8s provides an option to download the pod spec as yaml or json. 

Additionally, this can be used for gocd to define some pod templates in a repository for people to use? 

@sheroy , @arvindsv - WDYT?

**Comment by arvindsv** [comment]
Yes, I think it's a good idea too. If it's from a repo, then you can control it there and make a change (to say, update the image ID) and next run will automatically pick it up.

We do need better status updates in the GoCD job console (still). Currently, it's not clear what image is being used, etc. The plugin should put out more information and GoCD should use it better.
